version: '3'

services:
  app:
    build:
      context: node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 30s docker-entrypoint.sh
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    depends_on:
      - db
    command: bash -c "yarn && node index.js"

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d/:ro
      - ./mysql/data:/var/lib/mysql
    networks:
      - node-network

  nginx:
    container_name: nginx
    build:
      context: nginx
    restart: always
    tty: true
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - node-network
    ports:
      - "8080:80"
    depends_on:
      - app

networks:
  node-network:
    driver: bridge
